package com.example.schoolmanagement.util;

public class StringConstants {

    //SQL queries
    public static final String SORT_BY_SALARY_DESC_VR = "SELECT * FROM INSTRUCTOR JOIN VISITING_RESEARCHER ON INSTRUCTOR.ID = VISITING_RESEARCHER.ID ORDER BY HOURLY_SALARY DESC LIMIT 3";
    public static final String SORT_BY_SALARY_ASC_VR = "SELECT * FROM INSTRUCTOR JOIN VISITING_RESEARCHER ON INSTRUCTOR.ID = VISITING_RESEARCHER.ID ORDER BY HOURLY_SALARY ASC LIMIT 3";
    public static final String SORT_BY_SALARY_DESC_PI = "SELECT * FROM INSTRUCTOR JOIN PERMANENT_INSTRUCTOR ON INSTRUCTOR.ID = PERMANENT_INSTRUCTOR.ID ORDER BY FIXED_SALARY DESC LIMIT 3";
    public static final String SORT_BY_SALARY_ASC_PI = "SELECT * FROM INSTRUCTOR JOIN PERMANENT_INSTRUCTOR ON INSTRUCTOR.ID = PERMANENT_INSTRUCTOR.ID ORDER BY FIXED_SALARY ASC LIMIT 3";
    public static final String GET_GENDER_STATISTICS = "SELECT STUDENT.GENDER, COUNT(STUDENT.GENDER) AS Total FROM STUDENT GROUP BY GENDER";

    //Currency converter API URL
    public static final String CURRENCY_CONVERTER_API = "http://localhost:8081/api/";

}
